description: CLI 設定ファイル
config:
  name: cli
  version: 0.0.4
  description:
    short: CLI の short Description を記載してください
    logn: CLI の Long Description を記載してください
  github:
    repo:
      organization: ryurock
      name: go-cli-template
