name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.20.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Create artifact dir
        run: |
          mkdir -p artifacts/Linux

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o artifacts/Linux/ cmd/cli/main.go

      - name: Zip artifacts
        run: |
          zip -r linux-aarch64 .
        working-directory: ./artifacts/Linux

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/Linux/linux-aarch64.zip
          draft: true
          body_path: .github/CHANGELOG-template.md
